--- #YAML:1.0
name:               Catalyst-View-JavaScript
version:            0.99
abstract:           Cache and/or compress JavaScript output
author:
    - Moritz Onken <onken@houseofdesign.de>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::Runtime:    0
    JavaScript::Minifier::XS:  0
    Test::More:           0
    Test::WWW::Mechanize::Catalyst:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
